# Generated by Django 5.0.4 on 2024-05-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_city_location_city_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseller',
            name='company_address',
        ),
        migrations.AddField(
            model_name='reseller',
            name='pib',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
