# Generated by Django 5.0.4 on 2024-05-06 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blockeduser_user_alter_blockeduser_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
