# Generated by Django 5.0.4 on 2024-05-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_blockeduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedproduct',
            name='brand',
            field=models.CharField(default='apple', max_length=45),
            preserve_default=False,
        ),
    ]
