# Generated by Django 5.0.4 on 2024-05-30 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_supportedproduct_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.location'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.reseller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='delivery', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='imgs'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('customer', 'seller')},
        ),
    ]
