# Generated by Django 5.0.4 on 2024-05-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transaction_location_transaction_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
