# Generated by Django 5.0.4 on 2024-05-31 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transaction_total_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
    ]
